### PR TITLE
refactor(client): delete OutlineLauncher and OutlineTunnelStore

### PR DESCRIPTION
**Pull request by fortuna**
These have been major sources of pain.

Now we only need to edit the Cordova generated project to include the OutlinePlugin.

### CODE REVIEW

**Comment by fortuna** [comment]
This is now ready for review. I'm deleting nearly 900 lines and it still works!

**Review by jyyi1 — APPROVED** [review]
This looks great! Before merging, please make sure the auto-reconnect works when you turn the Wifi off and on again, or when you put the laptop to sleep.

**Comment by fortuna** [comment]
@jyyi1 Good idea. I tested all of these and they worked:
- Wifi off and on
- Sleep and awake
- Full restart

The full restart triggered the on-demand connection as expected.

**Comment by fortuna** [comment]
Small correction: we still edit the Cordova project to edit the app delegate for things like URL interception on macOS and the tray on macCatalyst and macOS. I think the iOS client shouldn't need anything else other than the plugin.

**Pull request merged**
