### PR TITLE
feat(client): dynamic name for dynamic keys

### PR DESCRIPTION
**Pull request by murka**
FYI: https://github.com/Jigsaw-Code/outline-server/issues/1561

### CODE REVIEW

**Comment by murka** [comment]
So, initial idea it was fetch and store keys name before connecting, but I have another idea, what about if hash-name is will be primary name, and we will take dynamic-key-name by fetch for each of session?

**Comment by murka** [comment]
wdyt: @fortuna @daniellacosse @sbruens @jyyi1

**Comment by fortuna** [comment]
Danil, could you please clarify what's the value of this feature? What is
it that you are trying to accomplish, and why does the existing hash
doesn't work for you?

**Comment by murka** [comment]
So, the existing hash system is not dynamic for key names, I gonna use this feature for information user, for example:

1) Quota in GB
2) Subscription info

The hash system is not working for this use cases.


image

**Comment by fortuna** [comment]
I see. So the feature you really need is a way to communicate quota usage! Or perhaps a generic message.
I think it would be better to have a focused feature rather than hack the name. Changing the name of an existing service can be very confusing! Let's discuss in the issue.

**Pull request closed without merging**
